### PR TITLE
Threadsafe

### PR DESCRIPTION
**Pull request by mike-kfed**
Hi, I am aware this PR doesn't merge because of some recent changes to master, but I wanted to wait for my other PR to be merged and then discuss async/thread compatibility. But I forgot about it, sorry.

I tried to use your crate with warp (a webserver) and the compiler wasn't happy about using static with async, so I rewrote it to use String and some other minor changes like replacing `load()` with a constructor called `new()`. This branch now successfully works as a in-memory htpasswd DB using a warp filter.

Since I am not sure you like those changes in general, I wanted to ask first if you're interested to make this compatible to async/threading before I try to merge your current master.

### CODE REVIEW

**Comment by rpasche** [comment]
ping. @mike-kfed @aQaTL I would really like to see this merged. I am fully new to Rust and I am also trying to build a simple "external basic http auth" service using Rust and the `warp` crate. The service should load multiple different `htpasswd` files (from filesystem) to be used by different `tenants` (separated by different routes) and I am finally struggling to build a  simple HashMap looking like `HashMap<String, Htpasswd>` because at some point, the compiler is always complaining that anything that I'm passing to `htpasswd_verify::load()` **does not live long enough**.

Pretty sure, a big part of my problem is my current lack of Rust knowledge.

My application is working fine, when I'm providing some "dummy" htpasswd data via a string literal.

And this PR looks like this would solve my problem.

Thank you for any feedback.

**Comment by aQaTL** [comment]
Sorry this took so long @mike-kfed . I've merged your PR, but I wanted to keep the option of zero copy checks. @rpasche The latest version has two options to construct Htpasswd struct: `Htpasswd::new_borrowed` and `Htpasswd::new_owned`. When using `new_borrowed`, it'll behave as it used to - it'll store &str references to the original string. But when using `new_owned`, String will be stored and the lifetime of the Htpasswd will be 'static. I hope that'll work for you.

**Comment by rpasche** [comment]
@aQaTL Oh...thank you very much for the quick reply now. I will test this very soon. :-)

**Comment by rpasche** [comment]
@aQaTL BIG thank you!! You just made my day (and probably a weekend!). Working like a charm now.

**Comment by mike-kfed** [comment]
> Sorry this took so long @mike-kfed . 

No worries, thanks for the merge! I figured you need the no-copy version and probably aren't happy with my fix ;)

**Pull request merged**
